version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    volumes:
      - ./django_admin:/fastapi_main_root/django_admin
    # environment:
    #   - ATLAS_CLUSTER_USERNAME=dp
    #   - ATLAS_CLUSTER_PASSWORD=ZrhXY3wvPqYoszrb
    #   - CLUSTER_DB_NAME=fastapi_main_microservice
    #   - PRDUCTS_COLLECTION_NAME=products
    #   - ATLAS_URI=mongodb+srv://dp:ZrhXY3wvPqYoszrb@cluster0.9wuzbib.mongodb.net/?retryWrites=true&w=majority
    command: "python django_admin/manage.py runserver 0.0.0.0:7000"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./django_admin/consumer.py:/fastapi_main_root/django_admin/consumer.py
    # environment:
    #   - ATLAS_CLUSTER_USERNAME=dp
    #   - ATLAS_CLUSTER_PASSWORD=ZrhXY3wvPqYoszrb
    #   - CLUSTER_DB_NAME=fastapi_main_microservice
    #   - PRDUCTS_COLLECTION_NAME=products
    #   - ATLAS_URI=mongodb+srv://dp:ZrhXY3wvPqYoszrb@cluster0.9wuzbib.mongodb.net/?retryWrites=true&w=majority
    command: 'python django_admin/consumer.py'
